### ISSUE TITLE
ServerSession is not defined

### ISSUE THREAD

**Issue by moritzmann1** [noNameWEB/Project-Cars-DS-LiveApp#17]
When clicking the /admin Link for an authenticated administrator, the app dies in development mode with the following message:

11/5/2015, 1:00:21 AM
First Server  offline
/opt/Project-Cars-DS-LiveApp/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
ReferenceError: ServerSession is not defined
    at Object.async.series.sessions (/opt/Project-Cars-DS-LiveApp/api/controllers/AdminController.js:30:9)
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:620:25
    at iterate (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/async/lib/async.js:626:21
    at /opt/Project-Cars-DS-LiveApp/api/controllers/AdminController.js:26:11
    at wrapper (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at returnResults (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:392:9)
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:272:16
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
    at /opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at Object.async.forEachOf.async.eachOf (/opt/Project-Cars-DS-LiveApp/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:227:20)

**Comment by surtic86** [comment]
Yes we know :) we are still in reworking the complete code. So the most Views will Brake today.
